# Generated by Django 4.1.7 on 2023-03-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_alter_cast_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogues',
            name='movie_name',
        ),
    ]
