# Generated by Django 4.1.7 on 2023-03-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_remove_dialogues_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogues',
            name='movie_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_dialogue', to='Movie.movie'),
        ),
    ]
